version: '3.5'
networks:
  lb-common:
    external: true
  anchore-network:
    external: false

services:
  # The primary API endpoint service
  api:
    image: anchore/anchore-engine:v0.10.0
    depends_on:
      - catalog
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=api
      - ANCHORE_ADMIN_USER=${ANCHORE_ADMIN_USER}
      - ANCHORE_ADMIN_PASSWORD=${ANCHORE_ADMIN_PASSWORD}
      - ANCHORE_DB_HOST=${ANCHORE_DB_HOST}
      - ANCHORE_DB_NAME=${ANCHORE_DB_NAME}
      - ANCHORE_DB_USER=${ANCHORE_DB_USER}
      - ANCHORE_DB_PASSWORD=${ANCHORE_DB_PASSWORD}
    command: ["anchore-manager", "service", "start", "apiext"]
    deploy:
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:anchore.local.io"
        - "traefik.docker.network=lb-common"
        - "traefik.port=8228"
        - "traefik.frontend.entryPoints=http"
        - "traefik.enable=true"
    networks:
      lb-common :
        aliases : 
          - anchore.local.io
      anchore-network :
    volumes:
      - /tmp:/tmp

  # Catalog is the primary persistence and state manager of the system
  catalog:
    image: anchore/anchore-engine:v0.10.0
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    expose:
      - 8228
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=catalog
      - ANCHORE_ADMIN_USER=${ANCHORE_ADMIN_USER}
      - ANCHORE_ADMIN_PASSWORD=${ANCHORE_ADMIN_PASSWORD}
      - ANCHORE_DB_HOST=${ANCHORE_DB_HOST}
      - ANCHORE_DB_NAME=${ANCHORE_DB_NAME}
      - ANCHORE_DB_USER=${ANCHORE_DB_USER}
      - ANCHORE_DB_PASSWORD=${ANCHORE_DB_PASSWORD}
    command: ["anchore-manager", "service", "start", "catalog"]
    networks:
      - anchore-network
    volumes:
      - /tmp:/tmp

  queue:
    image: anchore/anchore-engine:v0.10.0
    depends_on:
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=queue
      - ANCHORE_ADMIN_USER=${ANCHORE_ADMIN_USER}
      - ANCHORE_ADMIN_PASSWORD=${ANCHORE_ADMIN_PASSWORD}
      - ANCHORE_DB_HOST=${ANCHORE_DB_HOST}
      - ANCHORE_DB_NAME=${ANCHORE_DB_NAME}
      - ANCHORE_DB_USER=${ANCHORE_DB_USER}
      - ANCHORE_DB_PASSWORD=${ANCHORE_DB_PASSWORD}
    command: ["anchore-manager", "service", "start", "simplequeue"]
    networks:
      - anchore-network
    volumes:
      - /tmp:/tmp

  policy-engine:
    image: anchore/anchore-engine:v0.10.0
    depends_on:
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=policy-engine
      - ANCHORE_ADMIN_USER=${ANCHORE_ADMIN_USER}
      - ANCHORE_ADMIN_PASSWORD=${ANCHORE_ADMIN_PASSWORD}
      - ANCHORE_DB_HOST=${ANCHORE_DB_HOST}
      - ANCHORE_DB_NAME=${ANCHORE_DB_NAME}
      - ANCHORE_DB_USER=${ANCHORE_DB_USER}
      - ANCHORE_DB_PASSWORD=${ANCHORE_DB_PASSWORD}
    command: ["anchore-manager", "service", "start", "policy_engine"]
    networks:
      - anchore-network
    volumes:
      - /tmp:/tmp

  analyzer:
    image: anchore/anchore-engine:v0.10.0
    depends_on:
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=analyzer
      - ANCHORE_ADMIN_USER=${ANCHORE_ADMIN_USER}
      - ANCHORE_ADMIN_PASSWORD=${ANCHORE_ADMIN_PASSWORD}
      - ANCHORE_DB_HOST=${ANCHORE_DB_HOST}
      - ANCHORE_DB_NAME=${ANCHORE_DB_NAME}
      - ANCHORE_DB_USER=${ANCHORE_DB_USER}
      - ANCHORE_DB_PASSWORD=${ANCHORE_DB_PASSWORD}
    volumes:
      - /analysis_scratch
    command: ["anchore-manager", "service", "start", "analyzer"]
    networks:
      - anchore-network
    volumes:
      - /tmp:/tmp
