version: "3.3"

networks:
  portus_network:
    driver: overlay

services:
  portus:
    image: opensuse/portus:2.4.3
    environment:
      PORTUS_SECURITY_CLAIR_SERVER: ${PORTUS_SECURITY_CLAIR_SERVER}
      PORTUS_LOG_LEVEL: ${PORTUS_LOG_LEVEL}
      PORTUS_MACHINE_FQDN_VALUE: ${PORTUS_MACHINE_FQDN_VALUE}
      PORTUS_CHECK_SSL_USAGE_ENABLED: "false"
      CCONFIG_PREFIX: PORTUS
      PORTUS_DB_ADAPTER: ${PORTUS_DB_ADAPTER}
      PORTUS_DB_HOST: ${PORTUS_DB_HOST}
      PORTUS_DB_DATABASE: ${PORTUS_DB_DATABASE}
      PORTUS_DB_USERNAME: ${PORTUS_DB_USERNAME}
      PORTUS_DB_PASSWORD: ${PORTUS_DB_PASSWORD}
      PORTUS_DB_POOL: 5
      PORTUS_SECRET_KEY_BASE: ${PORTUS_SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/domain.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}
      RAILS_SERVE_STATIC_FILES: "true"
    expose:
      - "3000"
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    # links:
    #   - db
    networks:
      portus_network:
        aliases: 
          - "portus_app.local.io"

  background:
    image: opensuse/portus:2.4.3
    depends_on:
      - portus
      # - db
    environment:
      PORTUS_SECURITY_CLAIR_SERVER: ${PORTUS_SECURITY_CLAIR_SERVER}
      PORTUS_LOG_LEVEL: ${PORTUS_LOG_LEVEL}
      PORTUS_MACHINE_FQDN_VALUE: ${PORTUS_MACHINE_FQDN_VALUE}
      PORTUS_CHECK_SSL_USAGE_ENABLED: "false"
      CCONFIG_PREFIX: PORTUS​
      PORTUS_DB_ADAPTER: ${PORTUS_DB_ADAPTER}
      PORTUS_DB_HOST: ${PORTUS_DB_HOST}
      PORTUS_DB_DATABASE: ${PORTUS_DB_DATABASE}
      PORTUS_DB_USERNAME: ${PORTUS_DB_USERNAME}
      PORTUS_DB_PASSWORD: ${PORTUS_DB_PASSWORD}
      PORTUS_DB_POOL: 5​
      PORTUS_SECRET_KEY_BASE: ${PORTUS_SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/domain.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}
      RAILS_SERVE_STATIC_FILES: "true"
      PORTUS_LDAP_ENABLED: "false"
      PORTUS_BACKGROUND: "true"
    # links:
    #   - db
    networks:
      portus_network:
        aliases: 
          - "portus_background.local.io"

  # db:
  #   image: library/mariadb:10.0.23
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  #   environment:
  #     MYSQL_DATABASE: ${PORTUS_DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${PORTUS_DB_PASSWORD}
  #   networks:
  #     - portus_network

  registry:
    image: library/registry:2.6
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      # REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      # REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001

      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus_app.local.io:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registry_data
      - ./portus/secrets/portus.crt:/etc/docker/registry/domain.crt:ro
    ports:
      - 5000:5000
      - 5001:5001
    links:
      - portus
    networks:
      portus_network:
        aliases: 
          - "portus-registry.local.io"
          - "registry.local.io"

  clair:
    image: quay.io/coreos/clair:v2.0.2
    restart: unless-stopped
    # depends_on:
    #   - postgres
    # links:
    #   - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./portus/clair/clair.yml:/clair.yml
    command: [-config, /clair.yml]
    networks:
      - portus_network

  # postgres:
  #   image: library/postgres:10-alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${CLAIR_DB_PASSWORD}
  #     # POSTGRES_USER: ${CLAIR_DB_USER}
  #     # POSTGRES_DB: ${CLAIR_DB_DATABASE}
  #   networks:
  #     - portus_network
